version: "3"

services:

  web-slinker:
    container_name: web-slink
    image: web-slink
    ports:
      - "4321:4321"
    volumes:
      - sdb:/app/data
    depends_on:  # firstly build the cache container
      - cache-slinker

  db-slinker:
    container_name: db-slink
    image: db-slink
    volumes:
      - sdb:/app/data
    command: ./start-init.sh
    depends_on:  # firstly build the cache container
      - cache-slinker

  cache-slinker:
    container_name: cache-slink
    image: redis
    ports:
      - "6379:6379"  # redis default ports
    environment:
      - "REDIS_MAXMEMORY=100mb"  # max redis DB size - 100 MB
      - "REDIS_MAXMEMORY_POLICY=volatile-lru"  #  remove the less recently used keys when the max memory limit is reached

volumes:
  sdb:  # Shared database
    name: sdb
